export function clamp(v: number, min: number, max: number) { return v < min ? min : v > max ? max : v; }
export function lerp(a: number, b: number, t: number) { return a + (b - a) * t; }
export function smoothstep(edge0: number, edge1: number, x: number) { const t = clamp((x - edge0) / (edge1 - edge0), 0, 1); return t * t * (3 - 2 * t); }
export function hexToRgb(hex: string): [number, number, number] { const h = hex.replace('#', ''); if (h.length === 3) { return [parseInt(h[0] + h[0], 16), parseInt(h[1] + h[1], 16), parseInt(h[2] + h[2], 16)]; } return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)]; }
function permAndGrads(seed = 1337) { let s = seed|0 || 1; const rnd = () => (s = Math.imul(48271, s) % 2147483647) / 2147483647; const grads = new Array(256).fill(0).map(() => { const a = rnd() * Math.PI * 2; return { x: Math.cos(a), y: Math.sin(a) }; }); const perm = new Uint8Array(256); for (let i = 0; i < 256; i++) perm[i] = i; for (let i = 255; i > 0; i--) { const j = (rnd() * (i + 1)) | 0; const t = perm[i]; perm[i] = perm[j]; perm[j] = t; } const p = new Uint8Array(512); for (let i = 0; i < 512; i++) p[i] = perm[i & 255]; return { p, grads }; }
export function createValueNoise2D(seed = 1337) { const { p } = permAndGrads(seed); const fade = (t: number) => t * t * t * (t * (t * 6 - 15) + 10); const hash = (x: number, y: number) => p[(p[x & 255] + y) & 255] / 255; const noise = (x: number, y: number) => { const X = Math.floor(x); const Y = Math.floor(y); const xf = x - X; const yf = y - Y; const v00 = hash(X, Y); const v10 = hash(X + 1, Y); const v01 = hash(X, Y + 1); const v11 = hash(X + 1, Y + 1); const u = fade(xf); const v = fade(yf); const a = lerp(v00, v10, u); const b = lerp(v01, v11, u); return lerp(a, b, v); }; const fbm = (x: number, y: number, octaves = 5, gain = 0.5, lacunarity = 2) => { let a = 0, amp = 1, freq = 1; for (let i = 0; i < octaves; i++) { a += noise(x * freq, y * freq) * amp; amp *= gain; freq *= lacunarity; } return a; }; return { noise, fbm }; }
export function createNoise2D(seed = 1337) { const base = createValueNoise2D(seed); const fbm = (x: number, y: number, octaves = 5) => { const gain = 0.5; const lac = 2; let a = 0, amp = 1, freq = 1; let sumAmp = 0; for (let i = 0; i < octaves; i++) { a += base.noise(x * freq, y * freq) * amp; sumAmp += amp; amp *= gain; freq *= lac; } return a / sumAmp; }; return { noise: base.noise, fbm }; }
export function rand2(seed: number) { let s = seed|0 || 1; return () => (s = Math.imul(1664525, s) + 1013904223 | 0) >>> 0; }
export function mixRgb(a: [number, number, number], b: [number, number, number], t: number): [number, number, number] { return [Math.round(lerp(a[0], b[0], t)), Math.round(lerp(a[1], b[1], t)), Math.round(lerp(a[2], b[2], t))]; }
